# Generated by Django 3.2.6 on 2021-09-03 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_rename_comp_details_recruiter_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter_details',
            name='type',
        ),
    ]
