# Generated by Django 3.2.6 on 2021-09-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0002_first_selected_second_selected_shortlisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='stipend',
            field=models.IntegerField(default=0),
        ),
    ]
